name: python-template-test-4-cicd

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-template-test-4:${{ env.COMMIT_ID }}

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Modify values file
        shell: bash
        run: |
          pip install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/python-template-test-4/values-dev.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updates values.yaml with commit ${{ needs.ci.outputs.commit_id }}"
      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd\

      - name: ArgoCD Login
        shell: bash
        run: |
          argocd login argocd-server.argocd --insecure --grpc-web --username admin --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: Check if repository is registered in ArgoCD
        id: check_repo
        shell: bash
        run: |
          if grep -q python-template-test-4 argocd repo list; then
            echo "repo_exists=true" >> $GITHUB_OUTPUT
          else
            echo "repo_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Registers repository in ArgoCD
        if: steps.check_repo.outputs.repo_exists == 'false'
        shell: bash
        run: |
          argocd repo add https://github.com/odaavid-santos/python-template-test-4.git

      - name: Check if App already exists in ArgoCD
        id: check_app
        shell: bash
        run: |
          if grep -q python-template-test-4 argocd app list; then
            echo "app_exists=true" >> $GITHUB_OUTPUT
          else
            echo "app_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Creates app in ArgoCD
        if: steps.check_app.outputs.app_exists == 'false'
        shell: bash
        run: |
          argocd app create python-template-test-4 \
          --repo https://github.com/odaavid-santos/python-template-test-4.git \
          --path charts/python-template-test-4 \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace python-template-test-4 \
          --sync-option CreateNamespace=true

      - name: ArgoCD App Sync
        shell: bash
        run: |
          argocd app sync python-template-test-4
